import Head from "next/head"
import Link from "next/link"
import Footer from "../Footer"

const Blog = () => {
	return(
		<>
			<Head>
        <title>Mathias Ledesma - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> 
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<nav className="w-full flex text-center text-xl justify-end py-4 px-10 bg-gray-950/90 font-caslon">
				<div className="mx-4 w-16">
					<Link href="/">Home</Link>
				</div>
				<div className="mx-4 w-16">
					<Link href="/blog">Blog</Link>
				</div>
				<div className="mx-4 w-16">
					<a href="#contact">Contacto</a>
				</div>
			</nav>
			<div className="h-[calc(100vh-30vh)] md:h-auto">
				<h1 className="text-5xl bg-gray-950/60 mt-44 w-4/5 p-6 md:w-1/2 mx-auto text-center">En desarrollo...</h1>
			</div>
			<div className="absolute bottom-0 w-full">
				<Footer />
			</div>
		</>
	)
}

export default Blog