import Head from 'next/head'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Footer from './components/Footer'
import Projects from './components/Projects'
import Habilidades from './components/Habilidades'
import React from 'react'
import i18n from '@/i18n'
import { useTranslation } from 'react-i18next'


const inter:object = Inter({ subsets: ['latin'] })

const handleMenu = () => {
	let menu = document.querySelector('.hamburger') as HTMLElement;

	const toggleMenu = (event:any) => {
		let menuppal = document.querySelector( ".menuppal" ) as HTMLElement
		menuppal.classList.toggle("is_active")
  	event.preventDefault();
	}

	menu.addEventListener('click', toggleMenu);
}

export default function Home() {
	const [language, setLanguage] = React.useState("es-ES")

	const {t} = useTranslation();

	const handleChangeLanguage = () => {
		if(i18n.language == "es-ES"){
			i18n.changeLanguage("en-IN")
			setLanguage("en-IN")
		} else {
		i18n.changeLanguage("es-ES")
		setLanguage("es-ES")
		}
	}

  return (
    <>
      <Head>
        <title>Portafolio - Mathias Ledesma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> 
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<nav className='md:hidden fixed top-0 md:bottom-0 md:right-0 h-14 w-full 
					w-full bg-neutral-950/90 flex flex-row justify-center 
					text-sm md:text-lg z-10 md:[&>*]:scale-90'>
				<div className="hamburger" onClick={()=>handleMenu()}>
					<div className="_layer -top"></div>
					<div className="_layer -mid"></div>
					<div className="_layer -bottom"></div>
				</div>
				<nav className="menuppal bg-neutral-950/90">
					<ul>
						<li>
							<a 
								href="#sobremi"
								className='w-max mx-auto md:my-3 my-auto'>
								{t("About me")}
							</a>
						</li>
						<li>
							<a 
								href="#habilidades"
								className='w-max mx-auto md:my-3 my-auto'>
								{t("Skills")}
							</a>
						</li>
						<li>
							<a 
								href="#proyectos"
								className='w-max mx-auto md:my-3 my-auto'>
								{t("Projects")}
							</a>
						</li>
						<li>
							<button 
								onClick={()=>handleChangeLanguage()}
								className='w-max mx-auto md:my-3 my-auto'>
								{t("Change language")}
							</button>
						</li>
						<li>
							<a 
								href="#contacto"
								className='w-max mx-auto md:my-3 my-auto'>
								{t("Contact")}
							</a>
						</li>
					</ul>
				</nav>
				<h1 className="text-2xl my-auto">Portafolio</h1>
			</nav>
			<nav 
					className='fixed top-0 md:bottom-0 md:right-0 h-14 w-full 
					w-full bg-neutral-950/90 hidden md:flex md:flex-row justify-center 
					text-sm md:text-lg z-10 md:[&>*]:scale-90'
					>
					<a 
						href="#sobremi"
						className='w-max mx-auto md:my-3 my-auto hover:text-slate-500'
						>
						{t("About me")}
					</a>
					<a 
						href="#habilidades" 
						className='w-max mx-auto md:my-3 my-auto hover:text-slate-500'
						> 
						{t("Skills")}
					</a>
					<a 
						href="#proyectos" 
						className='w-max mx-auto md:my-3 my-auto hover:text-slate-500'
						>
						{t("Projects")}
					</a>
					<button 
						onClick={()=>handleChangeLanguage()}
						className='w-max mx-auto md:my-3 my-auto hover:text-slate-500'
						>
						{t("Change language")}
					</button>
					<a 
						href="#contacto" 
						className='w-max mx-auto md:my-3 my-auto hover:text-slate-500'
						>
						{t("Contact")}
					</a>
			</nav>

      <main 
				className="w-full"
				>
        <div 
					className='flex flex-col md:flex-row justify-center pt-56'
					>
					<Image 
						className='mx-auto h-max md:mx-10 mb-10 md:mb-0 rounded-xl'
						src="/resources/fotopng.png"
						alt='my photo' 
						width={170} 
						height={170}/>
					<div className="flex flex-col md:h-max md:flex-col">
						<h1 
							className='mx-auto ml-5 md:mr-20 md:ml-10 h-full md:pr-16 h-max
							md:pr-40 w-fit text-5xl md:text-7xl opacity-80'
							>
							Mathias Ledesma
						</h1>
						<h2 
							className='overflow-hidden whitespace-nowrap border-r-4 w-max opacity-80
								border-blue-500 w-0 m-0 m-auto animate-typing_mobile md:animate-typing text-4xl md:text-5xl'
							>
							{t("Full-Stack Developer")}
						</h2>
					</div>
					<div 
						className='mx-auto md:ml-48 mt-3 md:mb-20 pl-20 md:pl-40 
						mb-10 mt-5 w-fit opacity-80'
						>
						
					</div>
				</div>
				<section 
					className='h-max w-full flex flex-col 
						mt-10 px-12 md:px-20 py-12 md:relative'
					>
					<a id="sobremi"></a>
					<h3 
						className='text-4xl md:text-5xl md:mt-20 mx-auto md:mx-0'
						>
						{t("About me")}
					</h3>
					<p className='mt-12 md:mt-10 text-xl md:text-2xl font-light mx-auto'>
						{t("I am passionate about web development and have solid \
			experience and skills in the front-end field. A few years \
			ago, I entered the world of programming as a self-taught \
			person and have been perfecting my knowledge in this area. \
			Although I have the necessary foundation to work as a front-end \
			developer, I feel a greater affinity for logic and programming \
			than for design. For this reason, I decided to embark on a training \
			process in the field of back-end and, at the same time, carry out \
			various projects to accumulate experience. My goal is to prepare \
			for a career as a back-end or full-stack developer, as I am convinced \
			that my passion and skills in programming will lead me to achieve \
			my goals in this area.")}
					</p>
				</section>
				<a id="habilidades"></a>
				<Habilidades />
				<a id="proyectos"></a>
				<section 
					className='m-h-screen90 w-full my-10 px-12 md:px-20 
					py-12 md:relative'
					>
					<h3
						className='text-4xl md:text-5xl mb-16 mx-auto w-max md:mx-0'
					>
						{t("Projects")}
					</h3>
					<Projects />
				</section>
				<a id="contacto"></a>
				<Footer />
      </main>
    </>
  )
}

/*

Soy un apasionado del desarrollo web en 
						el cual tengo conocimientos y experiencia en el campo del front-end. 
						Hace unos años descubrí la programación y estudie de manera 
						autodidacta adquiriendo habilidades en esta área. Aunque tengo los 
						conocimientos para ser un desarrollador front-end, me gusta más la 
						lógica que el diseño, por lo que decidí comenzar a estudiar temas 
						relacionados al área de back-end y realizar proyectos para tener 
						experiencia al momento de trabajar como back-end o full-stack.

*/