import Head from 'next/head'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Footer from '../components/Footer'
import Projects from '../components/Projects'
import Habilidades from '../components/Habilidades'
import React from 'react'
import Nav from '../components/Nav/Nav'
import i18n from "@/i18n";
import { useTranslation } from 'react-i18next'
import ContactForm from '@/components/ContactForm'
import { sendEmail } from '@/services/emailjs'


const inter:object = Inter({ subsets: ['latin'] })

export default function Home() {
	const [language, setLanguage] = React.useState("es-ES")
	//evalua si se oprimio el boton enviar del formulario de contacto
	const [emailSend, setEmailSend] = React.useState(false)
	const {t} = useTranslation();
  return (
    <>
      <Head>
        <title>Portafolio - Mathias Ledesma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> 
        <link rel="icon" href="/favicon.png" />
      </Head>
			<Nav setLanguage={setLanguage}/>

      <main 
		className="w-full"
		>
        <div 
			className='flex flex-col lg:flex-row w-full lg:px-10 justify-center'
			>
			
			<div className="flex flex-row lg:flex-col mt-56 grow lg:h-max">
				<div className='w-full'>
					<h1 
						className='mx-auto lg:ml-5 lg:mr-20 lg:ml-10 h-full lg:pr-16 h-max
							lg:pr-40 w-max text-4xl lg:text-5xl opacity-80'>
						Mathias Ledesma
					</h1>
					<h2 
						className={`mx-auto overflow-hidden whitespace-nowrap border-r-4 mt-2 lg:mt-3 
						opacity-80 border-blue-500 w-0 m-0 lg:ml-32 text-2xl lg:text-3xl 
						${i18n.language == "es-ES" ? 
							"animate-typing_mobile_en lg:animate-typing_en" 
							: 
							"animate-typing_mobile lg:animate-typing"}`}>
						{t("Full-Stack Developer")}
					</h2>
				</div>
			</div>
			<div className="flex flex-col mt-14 lg:mt-56 grow lg:h-max">
				<p className='text-xl lg:text-2xl font-light mx-auto px-12'>
				{t("I am a curious and proactive fullstack web developer with \
			although with more affinity for the backend.")}
				</p>
				<a 
					className="mx-auto mt-10 bg-blue-950/90 hover:bg-blue-900 
						text-white font-bold py-2 px-4 rounded" 
					href="/resources/cv.pdf">
					{t("Download CV")}
				</a>
			</div>
		</div>
		<section 
			className='h-max w-full flex flex-col 
				mt-10 px-12 lg:px-20 py-12 lg:relative'
			>
			<a id="sobremi"></a>
			<h3 
				className='text-4xl lg:text-5xl lg:mt-20 mx-auto lg:mx-0'
				>
				{t("About me")}
			</h3>
			<p className='mt-12 lg:mt-10 text-xl lg:text-2xl font-light mx-auto text-justify'>
				{t("A few years \
			ago, I entered the world of programming as a self-taught \
			person and have been perfecting my knowledge in the area of ​​web development. \
			Although I have the necessary foundation to work as a front-end \
			developer, I feel a greater affinity for logic and programming \
			than for design. For this reason, I decided to embark on a training \
			process in the field of back-end and, at the same time, carry out \
			various projects to accumulate experience. My goal is to prepare \
			for a career as a back-end or full-stack developer, as I am convinced \
			that my passion and skills in programming will lead me to achieve \
			my goals in this area.")}
			</p>
		</section>
		<a id="habilidades"></a>
		<Habilidades />
		<a id="proyectos"></a>
		<section 
			className='m-h-screen90 w-full mt-10 mb-0 px-12 lg:px-20 
			py-12 lg:relative'
			>
			<h3
				className='text-4xl lg:text-5xl mb-16 mx-auto w-max lg:mx-0'
			>
				{t("Projects")}
			</h3>
			<Projects />
		</section>
		<a id="contacto"></a>
		<section 
			className='m-h-screen90 mt-0 mb-20 px-12 lg:px-20 py-12 lg:relative flex flex-col gap-10 
			text-center lg:text-start lg:flex-row items-center bg-neutral-950/20'
			>
			<div className='w-full flex flex-col gap-2'>
				<h5 className='mx-auto w-fit text-2xl'>{t("Do you need to create or improve your website?")}</h5>
				<p className='mx-auto w-fit'>{t("Complete the form to contact me.")}</p>
			</div>
			<ContactForm setEmailSend={setEmailSend} emailSend={emailSend}/>
		</section>
		<Footer />
      </main>
    </>
  )
}